<?php
require('../class/connect.php');
require('../class/db_sql.php');
require('class/user.php');
require('../data/dbcache/MemberLevel.php');
require LoadLang('pub/fun.php');
$link=db_connect();
$Elves=new mysqlquery();
$melve=$_POST['melve'];
if(empty($melve))
{
	$melve=$_GET['melve'];
}
eCheckCloseMods('member');//关闭模块
//绑定帐号
$tobind=(int)$_POST['tobind'];
if($tobind&&($melve=='login'||$melve=='register'))
{
	eCheckCloseMods('mconnect');//关闭模块
	eCheckCloseMemberConnect();//验证开启的接口
	session_start();
	include('../memberconnect/memberconnectfun.php');
}
if($melve=='login'||$melve=='exit')
{
	include('class/member_loginfun.php');
}
elseif($melve=='register')
{
	include('class/member_registerfun.php');
	include('class/member_modfun.php');
}
elseif($melve=='EditSafeInfo'||$melve=='EditInfo')
{
	include('class/member_editinfofun.php');
	include('class/member_modfun.php');
}
elseif($melve=='AddFava'||$melve=='DelFava_All'||$melve=='DelFava'||$melve=='AddFavaClass'||$melve=='EditFavaClass'||$melve=='DelFavaClass'||$melve=='MoveFava_All')
{
	include('../data/dbcache/class.php');
	include('class/favfun.php');
}
elseif($melve=='AddMsg'||$melve=='DelMsg'||$melve=='DelMsg_all')
{
	include('class/msgfun.php');
}
elseif($melve=='AddFriend'||$melve=='EditFriend'||$melve=='DelFriend'||$melve=='AddFriendClass'||$melve=='EditFriendClass'||$melve=='DelFriendClass')
{
	include('class/friendfun.php');
}
elseif($melve=='CardGetFen')
{
	include('class/membercomfun.php');
}
elseif($melve=='SendPassword'||$melve=='DoGetPassword'||$melve=='DoActUser'||$melve=='RegSend')
{
	include('class/member_actfun.php');
}

if($melve=="login")//登陆
{
	qlogin($_POST);
}
elseif($melve=="exit")//退出登陆
{
	qloginout($myuserid,$myusername,$myrnd);
}
elseif($melve=="register")//注册
{
	register($_POST);
}
elseif($melve=="EditSafeInfo")//修改安全信息
{
	EditSafeInfo($_POST);
}
elseif($melve=="EditInfo")//修改信息
{
	EditInfo($_POST);
}
elseif($melve=="AddFava")//增加收藏
{
	$cid=$_POST['cid'];
	$id=$_POST['id'];
	$classid=$_POST['classid'];
	$from=$_POST['from'];
	AddFava($id,$classid,$cid,$from);
}
elseif($melve=="DelFava_All")//删除收藏
{
	$favaid=$_POST['favaid'];
	DelFava_All($favaid);
}
elseif($melve=="DelFava")//删除收藏
{
	$favaid=$_GET['favaid'];
	DelFava($favaid);
}
elseif($melve=="CardGetFen")//点卡冲值
{
	$username=$_POST['username'];
	$reusername=$_POST['reusername'];
	$card_no=$_POST['card_no'];
	$password=$_POST['password'];
	CardGetFen($username,$reusername,$card_no,$password);
}
elseif($melve=="AddFavaClass")//增加收藏夹分类
{
	AddFavaClass($_POST);
}
elseif($melve=="EditFavaClass")//修改收藏夹分类
{
	EditFavaClass($_POST);
}
elseif($melve=="DelFavaClass")//删除收藏夹分类
{
	$cid=$_GET['cid'];
	DelFavaClass($cid);
}
elseif($melve=="MoveFava_All")//移动收藏夹
{
	$favaid=$_POST['favaid'];
	$cid=$_POST['cid'];
	MoveFava_All($favaid,$cid);
}
elseif($melve=="AddMsg")//发送短消息
{
	AddMsg($_POST);
}
elseif($melve=="DelMsg")//删除短消息
{
	DelMsg($_GET['mid']);
}
elseif($melve=="DelMsg_all")//批量删除短消息
{
	DelMsg_all($_POST['mid']);
}
elseif($melve=="AddFriend")//添加好友
{
	AddFriend($_POST);
}
elseif($melve=="EditFriend")//修改好友
{
	EditFriend($_POST);
}
elseif($melve=="DelFriend")//删除好友
{
	DelFriend($_GET);
}
elseif($melve=="AddFriendClass")//添加好友分类
{
	AddFriendClass($_POST);
}
elseif($melve=="EditFriendClass")//修改好友分类
{
	EditFriendClass($_POST);
}
elseif($melve=="DelFriendClass")//删除好友分类
{
	DelFriendClass($_GET['cid']);
}
elseif($melve=='SendPassword')//发送取回密码邮件
{
	SendGetPasswordEmail($_POST);
}
elseif($melve=='DoGetPassword')//重设密码
{
	DoGetPassword($_POST);
}
elseif($melve=='DoActUser')//激活帐号
{
	DoActUser($_GET);
}
elseif($melve=='RegSend')//重发激活邮件
{
	DoRegSend($_POST);
}
else
{printerror("ErrorUrl","history.go(-1)",1);}
db_close();
$Elves=null;
?>
